on:
  schedule:
    # TODO: use new zealand time?
    # Update on every 00:00 GMT+9 / WIT which means 15:00 UTC
    # Also sync timezone change to update.js/TIMEZONE_OFFSET
    - cron: "00 15 * * *"

jobs:
  update_katla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: install deps
        run: yarn install --prefer-offline
      - name: update new word
        run: yarn update
        env:
          SECRET_DATE: ${{ secrets.SECRET_DATE }}
          SECRET_WORD: ${{ secrets.SECRET_WORD }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
